<a href="https://colab.research.google.com/github/vanhuugiacuong/Dai_So_Tuyen_Tinh/blob/master/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Khởi tạo ma trận:

In [10]:
import numpy as np
F = np.eye(3, k=1)
print(F)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [9]:
import numpy as np
F = np.eye(3, k=0)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
import numpy as np
F = np.eye(3, k=-1)
print(F)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


2. Các phép xử lý đơn giản:

In [7]:
import numpy as np
C = np.array([[1, 2], [3, 4]])
A = np.array([[5, 6], [7, 8]])
print(np.linalg.matrix_rank(C))
# print(A.I) # Remove this line as .I is deprecated
print(np.linalg.inv(A)) # Use np.linalg.inv() instead
print(np.linalg.det(A))
print(A.T)

2
[[-4.   3. ]
 [ 3.5 -2.5]]
-2.000000000000005
[[5 7]
 [6 8]]


2. Tích (nhân) ma trận với ma trận
Mục này ôn lại một số kiến thức lý thuyết và giới thiệu một số loại ma trận đặc biệt.
2.1. Nhân ma trận

In [11]:
# Import thư viện
import numpy as np
from IPython.display import display

# ========================================
# 1. Khởi tạo ma trận đường chéo với np.eye
# ========================================
print("Ma trận np.eye(3, k=1):")
F = np.eye(3, k=1)
print(F)

print("\nMa trận np.eye(3, k=0):")
F = np.eye(3, k=0)
print(F)

print("\nMa trận np.eye(3, k=-1):")
F = np.eye(3, k=-1)
print(F)

# ========================================
# 2. Các phép xử lý đơn giản với ma trận
# ========================================

# Định nghĩa ma trận ví dụ
A = np.array([[1, 2], [3, 4]])
C = np.array([[2, 4], [6, 8]])

print("\nRank của ma trận C:")
print(np.linalg.matrix_rank(C))

print("\nNghịch đảo của ma trận A:")
print(np.linalg.inv(A))

print("\nĐịnh thức của ma trận A:")
print(np.linalg.det(A))

print("\nChuyển vị của ma trận A:")
print(A.T)

# Để sử dụng .H và .I, cần chuyển A thành np.matrix
A_matrix = np.matrix(A)

print("\nNghịch đảo A (dùng np.matrix):")
print(A_matrix.I)

print("\nChuyển vị liên hợp (Hermitian) A (dùng np.matrix):")
print(A_matrix.H)

# ========================================
# 3. Nhân ma trận
# ========================================
N = np.array([
    [6, 5, 3, 1],
    [3, 6, 2, 2],
    [3, 4, 3, 1]
])

G = np.array([
    [1.50, 1.00],
    [2.00, 2.50],
    [5.00, 4.50],
    [16.00, 17.00]
])

print("\nMa trận N:")
print(N)

print("\nMa trận G:")
print(G)

total_cost = np.dot(N, G)

print("\nTích N x G (total_cost):")
print(total_cost)


Ma trận np.eye(3, k=1):
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

Ma trận np.eye(3, k=0):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Ma trận np.eye(3, k=-1):
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

Rank của ma trận C:
2

Nghịch đảo của ma trận A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Định thức của ma trận A:
-2.0000000000000004

Chuyển vị của ma trận A:
[[1 3]
 [2 4]]

Nghịch đảo A (dùng np.matrix):
[[-2.   1. ]
 [ 1.5 -0.5]]

Chuyển vị liên hợp (Hermitian) A (dùng np.matrix):
[[1 3]
 [2 4]]

Ma trận N:
[[6 5 3 1]
 [3 6 2 2]
 [3 4 3 1]]

Ma trận G:
[[ 1.5  1. ]
 [ 2.   2.5]
 [ 5.   4.5]
 [16.  17. ]]

Tích N x G (total_cost):
[[50.  49. ]
 [58.5 61. ]
 [43.5 43.5]]


2.2. Ma trận khả nghịch

In [ ]:
import numpy as np

# Tạo một ma trận vuông A
A = np.array([[2, 1],
              [5, 3]])

# Kiểm tra định thức khác 0 → khả nghịch
det_A = np.linalg.det(A)
print("Định thức của A:", det_A)

if det_A != 0:
    # Tính ma trận nghịch đảo
    A_inv = np.linalg.inv(A)
    print("\nMa trận nghịch đảo A⁻¹:")
    print(A_inv)

    # Kiểm tra A * A⁻¹ = I
    identity = np.dot(A, A_inv)
    print("\nKiểm tra A * A⁻¹:")
    print(identity)
else:
    print("Ma trận A không khả nghịch (det = 0)")

2.3. Ma trận hội tụ

In [12]:
import numpy as np

print("===== Ma trận A =====")
A = np.array([[0, 1], [1, 0]])
print("A =\n", A)

temp = A.dot(A)
print("\nA^2 =\n", temp)

k = 6
print("\nCác lũy thừa tiếp theo của A:")
for i in range(k - 1):
    temp = temp.dot(A)
    print(f"A^{i+3} =\n{temp}")
    print('---')

print("\n>>> Nhận xét:")
print("Ma trận A là ma trận hoán vị (swap), có chu kỳ lặp lại mỗi 2 lần:")
print("A^1 = swap, A^2 = I, A^3 = A, A^4 = I, ... → phân kỳ theo chu kỳ.")

# ---------------------------------

print("\n\n===== Ma trận B =====")
B = np.array([[0, -1], [-1, 0]])
print("B =\n", B)

temp = B.dot(B)
print("\nB^2 =\n", temp)

k = 5
print("\nCác lũy thừa tiếp theo của B:")
for i in range(k - 1):
    temp = temp.dot(B)
    print(f"B^{i+3} =\n{temp}")
    print('---')

print("\n>>> Nhận xét:")
print("Ma trận B cũng có chu kỳ lặp lại sau mỗi 2 lần:")
print("B^2 = I, B^3 = B, B^4 = I, ... → phân kỳ theo chu kỳ.")

# ---------------------------------

print("\n\n===== Ma trận C (Hội tụ) =====")
C = np.array([[1, 0, 0], [0, 0.5, 1], [0, 0, 0.5]])
print("C =\n", C)

temp = C.dot(C)
print("\nC^2 =\n", temp)

# Lũy thừa lớn
k = 1000
for i in range(k - 1):
    temp = temp.dot(C)

print("\n>>> C^1000 =\n", temp)
print(">>> Nhận xét:")
print("Khi T → ∞, các phần tử ngoài đường chéo bị triệt tiêu, C^T hội tụ về dạng tam giác trên.")

# Tính tiếp 1000 lần nữa
for i in range(k - 1):
    temp = temp.dot(C)

print("\n>>> C^2000 =\n", temp)
print(">>> Nhận xét:")
print("Càng nhân tiếp, ma trận càng hội tụ về trạng thái ổn định — chỉ còn các giá trị nhỏ dần trên đường chéo.")


===== Ma trận A =====
A =
 [[0 1]
 [1 0]]

A^2 =
 [[1 0]
 [0 1]]

Các lũy thừa tiếp theo của A:
A^3 =
[[0 1]
 [1 0]]
---
A^4 =
[[1 0]
 [0 1]]
---
A^5 =
[[0 1]
 [1 0]]
---
A^6 =
[[1 0]
 [0 1]]
---
A^7 =
[[0 1]
 [1 0]]
---

>>> Nhận xét:
Ma trận A là ma trận hoán vị (swap), có chu kỳ lặp lại mỗi 2 lần:
A^1 = swap, A^2 = I, A^3 = A, A^4 = I, ... → phân kỳ theo chu kỳ.


===== Ma trận B =====
B =
 [[ 0 -1]
 [-1  0]]

B^2 =
 [[1 0]
 [0 1]]

Các lũy thừa tiếp theo của B:
B^3 =
[[ 0 -1]
 [-1  0]]
---
B^4 =
[[1 0]
 [0 1]]
---
B^5 =
[[ 0 -1]
 [-1  0]]
---
B^6 =
[[1 0]
 [0 1]]
---

>>> Nhận xét:
Ma trận B cũng có chu kỳ lặp lại sau mỗi 2 lần:
B^2 = I, B^3 = B, B^4 = I, ... → phân kỳ theo chu kỳ.


===== Ma trận C (Hội tụ) =====
C =
 [[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]

C^2 =
 [[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]

>>> C^1000 =
 [[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631

2.4. Ma trận Markov

In [ ]:
import numpy as np

# Ma trận Markov ban đầu
M = np.array([[0.8, 0.3],
              [0.2, 0.7]])

print("M =\n", M)

# Tính M^2
M2 = M.dot(M)
print("\nM^2 =\n", M2)

# Tính M^3
M3 = M2.dot(M)
print("\nM^3 =\n", M3)

# Tính M^100
MM = M3.copy()
for i in range(97):  # đã có M3 rồi nên chỉ cần nhân thêm 97 lần
    MM = MM.dot(M)

print("\nM^100 =\n", MM)

print("\n>>> Nhận xét:")
print("M^100 hội tụ về ma trận mà các cột giống nhau.")
print("→ Thị phần ổn định giữa A và B:")
print("Hãng A chiếm khoảng", round(MM[0, 0], 2), ", Hãng B khoảng", round(MM[1, 0], 2))


3.1. Khái niệm về tách ma trận

In [ ]:
import numpy as np

# Tạo 2 vector/mảng (ma trận nhỏ hơn)
# B có kích thước (4 x 1)
B = np.array([
    [5],
    [7],
    [6],
    [8]
])

# C có kích thước (1 x 4)
C = np.array([
    [1, 1, 1, 1]
])

# Tính tích A = B x C, kết quả là ma trận (4 x 4)
A = B @ C  # hoặc dùng B.dot(C)
print("Ma trận A được khôi phục từ B và C là:\n")
print(A)


3.2. Phân rã ma trận LU

In [ ]:
import numpy as np
from scipy import linalg

# Khai báo ma trận M
M = np.array([
    [0.8, 0.3],
    [0.2, 0.7]
])

# Thực hiện phân rã LU
P, L, U = linalg.lu(M)

# In kết quả
print("Ma trận P (hoán vị):")
print(P)

print("\nMa trận L (tam giác dưới):")
print(L)

print("\nMa trận U (tam giác trên):")
print(U)

# Kiểm tra lại: L.dot(U) có bằng P.dot(M) không?
print("\nL.dot(U):")
print(L.dot(U))

print("\nP.dot(M):")
print(P.dot(M))

# Kiểm tra sai số giữa 2 kết quả
print("\nSai số (P @ M - L @ U):")
print(np.round(P @ M - L @ U, 10))


4. Bài toán ứng dụng 1 – Căn bản về mật mã học, mã hóa thông tin, mật khẩu

In [ ]:
import numpy as np

# Chuỗi gốc được chuyển thành các số
X = np.array([
    [13, 11, 17],
    [1, 0, 11],
    [17, 34, 5],
    [0, 6, 26],
    [33, 0, 14],
    [12, 9, 34],
    [25, 35, 35]  # Dòng cuối sẽ chứa mã 35 (không mã), có thể bỏ nếu cần
])

# Ma trận khóa (3x3)
M = np.array([
    [3, 1, -2],
    [2, -1, 1],
    [1, -1, -4]
])

Y = X @ M.T  # Nhân với chuyển vị để xử lý đúng dạng hàng x cột
print("Dãy mã hóa:")
print(Y)

# Tính nghịch đảo ma trận M
M_inv = np.linalg.inv(M)

# Giải mã: nhân mã hóa với nghịch đảo
X_decoded = np.round(Y @ M_inv.T).astype(int)  # Làm tròn và ép kiểu int để khôi phục
print("Dãy khôi phục lại:")
print(X_decoded)

5. Bài toán ứng dụng 2 – Bài toán loan tin

In [ ]:
import numpy as np

A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])

temp = A.dot(A)
print("A^2:")
print(temp)

 ***BÀI TẬP CHƯƠNG 3 ***

Câu 1: Hãy viết chương trình bằng Python hoặc sử dụng thư viện numpy/sympy để:


In [ ]:
import numpy as np

# a. Chọn ma trận khả nghịch 3x3
A = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [1, 0, 0]
])

# Kiểm tra khả nghịch
det = np.linalg.det(A)
if det == 0:
    print("Ma trận không khả nghịch.")
    exit()
else:
    print("Ma trận A khả nghịch. Định thức =", det)

A_inv = np.linalg.inv(A)

# b. Nhập họ và tên hoặc MSSV
text = input("Nhập họ và tên hoặc mã số sinh viên: ")

# c. Mã hóa
# Chuyển chuỗi sang mã ASCII
ascii_vals = [ord(c) for c in text]

# Thêm số 0 để chia hết cho 3
while len(ascii_vals) % 3 != 0:
    ascii_vals.append(0)

# Mã hóa từng nhóm 3 phần tử
cipher = []
for i in range(0, len(ascii_vals), 3):
    vec = np.array(ascii_vals[i:i+3]).reshape(3, 1)
    enc_vec = A.dot(vec)
    cipher.append(enc_vec)

print("\nMã hóa (danh sách các vector mã hóa):")
for vec in cipher:
    print(vec.T)

# d. Giải mã
decoded = []
for vec in cipher:
    dec_vec = A_inv.dot(vec)
    decoded.extend(dec_vec.flatten().round().astype(int))

# Loại bỏ số 0 padding nếu có
decoded_text = ''.join([chr(x) for x in decoded if x != 0])

print("\nGiải mã:")
print(decoded_text)

Câu 2: Tính toán phân số từ liên phân số (continued fractions)

In [ ]:
import numpy as np
from fractions import Fraction

def continued_fraction_to_fraction(cf):
    # cf: list chứa các phần tử [a0, a1, ..., an]
    M = np.array([[cf[0], 1],
                  [1,     0]])

    for ai in cf[1:]:
        Mi = np.array([[ai, 1],
                       [1,  0]])
        M = np.dot(Mi, M)

    numerator = M[0, 0]
    denominator = M[1, 0]
    return Fraction(numerator, denominator)

# Ví dụ
cf = [3, 1, 2]  # tương ứng với 8/3
frac = continued_fraction_to_fraction(cf)
print(f"Dạng phân số: {frac} = {frac.numerator}/{frac.denominator}")