<a href="https://colab.research.google.com/github/vanhuugiacuong/Dai_So_Tuyen_Tinh/blob/master/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Sử dụng array và matrix trong numpy
Dưới đây là tóm gọn một số lưu ý khi sử dụng kiểu matrix và array trong gói NumPy:
1.1. Thông tin tóm gọn

In [ ]:
import numpy as np

D = np.array([[1, 2], [3, 4]])

# Trường hợp lỗi do E chưa được khởi tạo
# np.copyto(E, D)  # Gây lỗi: NameError hoặc UnboundLocalError

# Đúng cách: khởi tạo E trước
E = np.array([[1, 2], [3, 5]])
np.copyto(E, D)
print(E)
# Kết quả: [[1 2]
#           [3 4]]

1.2. Nên và không nên sử dụng kiểu dữ liệu numpy.matrix

In [ ]:
import numpy as np

x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'
C = np.matrix([[x, y], [1, 2]])
print(C)
# Kết quả:
# [[[['a' 'b']
#    ['c' 'd']] 'x']
#  [1 2]]
import numpy as np

# Sẽ gây lỗi:
# A = np.matrix([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# → ValueError: shape too large to be a matrix

# Dùng array thay thế
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(A)
# Kết quả:
# [[[1 2]
#   [3 4]]
#  [[5 6]
#   [7 8]]]

1.3. Đối tượng matrix từ các hàm trong gói numpy.matlib

In [ ]:
from numpy import matlib

# Ma trận đơn vị
G = matlib.identity(5)
print(G)
# [[1. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0.]
#  [0. 0. 1. 0. 0.]
#  [0. 0. 0. 1. 0.]
#  [0. 0. 0. 0. 1.]]

# Ma trận ngẫu nhiên chuẩn (Gaussian)
H = matlib.randn(3, 2)
print(H)
# Ví dụ kết quả (ngẫu nhiên):
# [[ 0.38 -1.25]
#  [ 1.03  0.11]
#  [-0.67  0.92]]

# Ma trận toàn số 0
K = matlib.zeros([4, 4])
print(K)
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]

2. Ứng dụng 2 –Liên phân số và số 
2.1. Liên phân số


In [2]:
import numpy as np

# Dãy liên phân số biểu diễn số π (có thể thêm phần tử để tăng độ chính xác)
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]

# Khởi tạo ma trận M ban đầu
for i in range(len(c)):
    ci = np.asmatrix([[c[i], 1], [1, 0]])
    if i == 0:
        M = ci
    else:
        M = M.dot(ci)

# Kết quả gần đúng số π
print("Ma trận M:")
print(M)
print("\nSố Pi gần đúng:")
print(M[0, 0] / M[1, 0])

Ma trận M:
[[165707065  80143857]
 [ 52746197  25510582]]

Số Pi gần đúng:
3.1415926535897936


3. Về phân tích hồi quy tuyến tính
[Mục này cung cấp thêm kiến thức cho sinh viên về dạng phương trình skiny, hệ phương trình có
số phương trình nhiều hơn số ẩn]

In [3]:
import numpy as np

# Dữ liệu đầu vào
# X: ma trận (n, 2) gồm cột 1 là hằng số 1, cột 2 là ngày đo
X = np.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4],
    [1, 5]
])

# Y: chiều cao đo được từng ngày
Y = np.array([1, 2, 4, 4, 6])

# Bước 1: Tính X.T (ma trận chuyển vị)
XT = X.T

# Bước 2: Tính A1 = (X^T X)^-1
A1 = np.linalg.inv(XT.dot(X))

# Bước 3: Tính A2 = X^T Y
A2 = XT.dot(Y)

# Bước 4: Tính nghiệm A = [a0, a1] với Y = a0 + a1 * x
A = A1.dot(A2)

print("Hệ số hồi quy:", A)
print(f"Phương trình gần đúng: y = {A[0]:.4f} + {A[1]:.4f} * x")

# Bước 5: Tính các giá trị y dự đoán và sai số bình phương
Y_pred = X.dot(A)
errors = Y - Y_pred
squared_errors = errors ** 2
total_error = np.sum(squared_errors)

print("Sai số từng điểm:", squared_errors)
print("Tổng sai số bình phương:", total_error)


Hệ số hồi quy: [-0.2  1.2]
Phương trình gần đúng: y = -0.2000 + 1.2000 * x
Sai số từng điểm: [1.77986742e-29 4.00000000e-02 3.60000000e-01 3.60000000e-01
 4.00000000e-02]
Tổng sai số bình phương: 0.8000000000000003


BÀI TẬP CHƯƠNG 5


In [4]:
import numpy as np
dulieu = [10.0, 8, 7, 5, 2]
def bpcuctieu(a):  # a là danh sách giá trị y (lượng thuốc)
    b = []     # chứa giá trị x (thời gian)
    o1 = []    # chứa toàn số 1 để tạo ma trận X với 2 cột [1, x]
    for i in range(len(a)):
        o1.append(1.0)
        b.append(float(i))  # thời gian tính từ 0, 1, 2,...

    # X là ma trận 2xN (sẽ transpose sau)
    x = np.array([o1, b])            # x.shape = (2, n)
    u = np.dot(x, x.T)               # tính X·X^T
    y = np.array(a)                  # y: vector lượng thuốc
    u_inv = np.linalg.inv(u)        # (X·X^T)^-1
    v = np.dot(u_inv, x)            # v = (X·X^T)^-1 · X
    A = np.dot(v, y)                # A = v · Y
    return A  # A[0]: hệ số tự do, A[1]: hệ số của x


A = bpcuctieu(dulieu)
print(f"Phương trình tuyến tính: y = {A[0]:.2f} + {A[1]:.2f} * x")


Phương trình tuyến tính: y = 10.20 + -1.90 * x
