<a href="https://colab.research.google.com/github/vanhuugiacuong/Dai_So_Tuyen_Tinh/blob/master/lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.2. Tích vô hướng và ứng dụng

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.inner(a,b))  # hoặc np.dot(a,b)

32


✅ Chuẩn (Norm): Độ dài vector
Chuẩn bậc 2:
‖u‖ = √<u, u>

Chuẩn bậc 1:
‖u‖₁ = ∑|uᵢ|

Tổng quát:
‖u‖ₚ = (∑|uᵢ|ᵖ)¹/ᵖ

Ví dụ:

 2. Tổ hợp tuyến tính (Linear Combination)


In [2]:
import numpy as np

# Tổng khối lượng
m = 10

# Các vector vị trí
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])

# Mảng vector xếp thành ma trận
M = np.array([v1, v2, v3, v4])     # (4,3)
MT = M.transpose()                # (3,4) để nhân với trọng lượng (4,)

# Vector trọng lượng từng phụ tùng
mi = np.array([2, 5, 2, 1])

# Tính trọng tâm
v = (1.0 / m) * MT.dot(mi)

print("MT (transpose):")
print(MT)

print("Trọng tâm của hệ là:")
print(v)

MT (transpose):
[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
Trọng tâm của hệ là:
[1.3 0.9 0. ]


3.1. Bài toán dẫn nhập: Mô hình Markov

In [3]:
import numpy as np

# Ma trận chuyển trạng thái
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])

# Trạng thái ban đầu
v0 = np.array([0.95, 0.05])

# Tính A^100
A_100 = np.linalg.matrix_power(A, 100)

# Trạng thái sau 100 tuần
v100 = A_100 @ v0

print("A^100:")
print(A_100)

print("Trạng thái sau 100 tuần:")
print(v100)

A^100:
[[0.98550725 0.9855069 ]
 [0.01449275 0.0144931 ]]
Trạng thái sau 100 tuần:
[0.98550723 0.01449277]


3.2.Trị riêng và vector riêng của ma trận

In [4]:
import numpy as np

A = np.array([[1, 6],
              [5, 2]])
u = np.array([6, -5])

Au = A @ u
right_side = -4 * u

print("A·u =", Au)
print("-4·u =", right_side)
print("Equal?", np.allclose(Au, right_side))


# 3. Tìm trị riêng bằng SymPy
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)

A = sympy.Matrix([[2, 3], [3, -6]])
char_poly = sympy.det(Lambda * I - A)

# Giải trị riêng
eigenvalues = sympy.solve(sympy.Eq(char_poly, 0), Lambda)
print("Trị riêng (gốc):", eigenvalues)
print("Trị riêng (gần đúng):", [sympy.N(val, 4) for val in eigenvalues])

A·u = [-24  20]
-4·u = [-24  20]
Equal? True


3.3.Ứng dụng của trị riêng và vector riêng

In [5]:
# Bước 1: Tạo ma trận và trị riêng
import numpy as np
from numpy.linalg import inv

# Ma trận A
A = np.array([[2, 3],
              [3, -6]])

# Ma trận D (trị riêng trên đường chéo)
D = np.array([[-7, 0],
              [0, 3]])

# Ma trận P (vector riêng xếp thành cột)
P = np.array([[-1/3, 3],
              [1,    1]])

# Tính nghịch đảo của P
P_inv = inv(P)
print("P^(-1) =")
print(P_inv)

# Bước 2: Kiểm tra chéo hóa
# 𝐴
# =
# 𝑃
# 𝐷
# 𝑃
# −
# 1
# A=PDP
# −1
# Kiểm tra A·P = P·D
print("A·P =")
print(A @ P)

print("P·D =")
print(P @ D)

# Bước 3: Tính
# 𝐴
# 1000
# A
# 1000
#   bằng chéo hóa

# Tính D^1000 dễ vì D là đường chéo
D_1000 = np.linalg.matrix_power(D, 1000)

# Tính A^1000 bằng công thức A^k = P·D^k·P⁻¹
A_1000 = P @ D_1000 @ P_inv

print("A^1000 =")
print(A_1000)

print("D^2 =")
print(np.linalg.matrix_power(D, 2))

P^(-1) =
[[-0.3  0.9]
 [ 0.3  0.1]]
A·P =
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
P·D =
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
A^1000 =
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]
D^2 =
[[49  0]
 [ 0  9]]


✅ Câu 1: Trắc nghiệm
Câu hỏi: Lệnh nào tính chuẩn 2 (norm 2) của vector a = np.array([1,2,3])?

Nhắc lại, chuẩn 2 được định nghĩa là:

∥
𝑎
∥
=
𝑎
1
2
+
𝑎
2
2
+
𝑎
3
2
=
𝑎
⋅
𝑎
=
inner
(
𝑎
,
𝑎
)
∥a∥=
a
1
2
​
 +a
2
2
​
 +a
3
2
​

​
 =
a⋅a
​
 =
inner(a,a)
​

Phân tích:
a. np.sqrt(a.dot(a)) ✅ đúng

b. np.sqrt(a @ a) ✅ đúng (dấu @ là toán tử dot product từ Python 3.5+)

c. np.sqrt(np.inner(a,a)) ✅ đúng

d. mag = lambda x : math.sqrt(sum(i**2 for i in x))
→ đúng về mặt ý tưởng, nhưng cần import math trước

✅ Đáp án đúng là: Tất cả các phương án a, b, c, d đều tính đúng chuẩn 2 (nếu có import math cho d).

In [6]:
# ✅ Câu 2: Viết chương trình
# a. Tính khoảng cách giữa 2 vector u và v

import numpy as np

def vector_distance(u, v):
    u = np.array(u)
    v = np.array(v)
    return np.linalg.norm(u - v)

# Test
u = [1, 2, 3]
v = [4, 0, -1]
print("Khoảng cách giữa u và v:", vector_distance(u, v))

# b. Tính góc
# 𝜃
# θ giữa 2 vector u và v
import numpy as np
import math

def angle_between(u, v):
    u = np.array(u)
    v = np.array(v)
    dot_product = np.dot(u, v)
    norm_u = np.linalg.norm(u)
    norm_v = np.linalg.norm(v)
    cos_theta = dot_product / (norm_u * norm_v)
    angle_rad = math.acos(np.clip(cos_theta, -1.0, 1.0))  # clip để tránh lỗi do làm tròn
    angle_deg = math.degrees(angle_rad)
    return angle_deg

# Test
u = [1, 0]
v = [0, 1]
print("Góc giữa u và v (độ):", angle_between(u, v))

# c. Tính phép chiếu trực giao của u lên v

import numpy as np

def orthogonal_projection(u, v):
    u = np.array(u)
    v = np.array(v)
    coefficient = np.dot(u, v) / np.dot(v, v)
    proj = coefficient * v
    return proj

# Test
u = [1, 2]
v = [3, 0]
print("Phép chiếu của u lên v:", orthogonal_projection(u, v))

Khoảng cách giữa u và v: 5.385164807134504
Góc giữa u và v (độ): 90.0
Phép chiếu của u lên v: [1. 0.]
