<a href="https://colab.research.google.com/github/vanhuugiacuong/Dai_So_Tuyen_Tinh/blob/master/ThiThucHanh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1:

In [1]:
import numpy as np
from numpy.linalg import norm
from math import degrees, acos

# Khởi tạo vector và ma trận
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([
    [2, -1, 3],
    [1, 4, -2],
    [0, 2, 5]
])

# a) Tính tổng và tích số
sum_AB = A + B
scalar_combo = 2*A + 3*B

print("a)")
print("A + B =", sum_AB)
print("2A + 3B =", scalar_combo)

# b) Tích vô hướng và góc giữa hai vector
dot_product = np.dot(A, B)
cos_theta = dot_product / (norm(A) * norm(B))
angle_degrees = degrees(acos(cos_theta))

print("\nb)")
print("A · B =", dot_product)
print("Góc giữa A và B (độ) =", round(angle_degrees, 3))

# c) Tích ma trận C * C^T
C_CT = C @ C.T

print("\nc)")
print("C * C^T =\n", C_CT)

a)
A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]

b)
A · B = -5
Góc giữa A và B (độ) = 99.594

c)
C * C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


Câu 2:

In [2]:
import numpy as np

# Khởi tạo ma trận M và N
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

# a) Tích ma trận M * N
product = M @ N

# b) Định thức của M
det_M = np.linalg.det(M)

# c) Hạng của ma trận N
rank_N = np.linalg.matrix_rank(N)

# In kết quả
print("a) M x N =\n", product)
print("\nb) Định thức của M =", round(det_M, 3))
print("\nc) Hạng của ma trận N =", rank_N)


a) M x N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b) Định thức của M = 409.0

c) Hạng của ma trận N = 4


Câu 3:

In [3]:
import numpy as np

# a) Khởi tạo ma trận P và vector B
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])

B = np.array([6, 8, 3, 7])

# Kiểm tra khả nghịch và tính nghịch đảo
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P:\n", np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch vì định thức bằng 0.")

# b) Giải hệ phương trình X = P^(-1) * B
X = P_inv @ B
print("\nb) Nghiệm của hệ phương trình (x, y, z, w):\n", np.round(X, 3))

# c) Kiểm tra nghiệm: P @ X ≈ B
check = P @ X
print("\nc) Kiểm tra P * X:\n", np.round(check, 3))
print("Vector B ban đầu:\n", B)


a) Ma trận nghịch đảo của P:
 [[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]

b) Nghiệm của hệ phương trình (x, y, z, w):
 [2.    1.714 0.429 0.857]

c) Kiểm tra P * X:
 [6. 8. 3. 7.]
Vector B ban đầu:
 [6 8 3 7]


Câu 4

In [4]:
import numpy as np

# Khởi tạo ma trận Q
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

# a) Tính giá trị riêng và vector riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)

print("a) Giá trị riêng:")
for i, val in enumerate(eigenvalues):
    print(f"λ{i+1} =", round(val, 3))

# b) Vector riêng chưa chuẩn hóa
print("\nb) Vector riêng tương ứng:")
for i in range(len(eigenvalues)):
    print(f"Vector riêng v{i+1}:\n", np.round(eigenvectors[:, i], 3))

# c) Chuẩn hóa vector riêng
print("\nc) Vector riêng đã chuẩn hóa:")
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    v_norm = v / np.linalg.norm(v)
    print(f"v{i+1} chuẩn hóa:\n", np.round(v_norm, 3))


a) Giá trị riêng:
λ1 = (6.355+0j)
λ2 = (2.822+1.077j)
λ3 = (2.822-1.077j)

b) Vector riêng tương ứng:
Vector riêng v1:
 [ 0.748+0.j -0.189+0.j  0.636+0.j]
Vector riêng v2:
 [-0.374+0.342j  0.095+0.574j  0.636+0.j   ]
Vector riêng v3:
 [-0.374-0.342j  0.095-0.574j  0.636-0.j   ]

c) Vector riêng đã chuẩn hóa:
v1 chuẩn hóa:
 [ 0.748+0.j -0.189+0.j  0.636+0.j]
v2 chuẩn hóa:
 [-0.374+0.342j  0.095+0.574j  0.636+0.j   ]
v3 chuẩn hóa:
 [-0.374-0.342j  0.095-0.574j  0.636-0.j   ]


/tmp/ipython-input-4-856830617.py:15: DeprecationWarning: The Python built-in `round` is deprecated for complex scalars, and will raise a `TypeError` in a future release. Use `np.round` or `scalar.round` instead.
  print(f"λ{i+1} =", round(val, 3))


Câu 5:

In [5]:
import numpy as np

# Khởi tạo ma trận R và vector b
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])

b = np.array([12, 5, 9])

# a) Giải hệ phương trình Rx = b
x_solve = np.linalg.solve(R, b)
print("a) Nghiệm bằng np.linalg.solve():\n", np.round(x_solve, 3))

# b) Kiểm tra khả nghịch và tính nghịch đảo
det_R = np.linalg.det(R)
print("\nb) Định thức của R =", round(det_R, 3))

if det_R != 0:
    R_inv = np.linalg.inv(R)
    print("Ma trận R khả nghịch. Ma trận nghịch đảo:\n", np.round(R_inv, 3))
    x_inv = R_inv @ b
    print("Nghiệm bằng R^(-1) * b:\n", np.round(x_inv, 3))
    print("Hai nghiệm giống nhau:", np.allclose(x_solve, x_inv))
else:
    print("Ma trận R không khả nghịch.")

# c) Chuẩn Frobenius
fro_norm = np.linalg.norm(R, 'fro')
print("\nc) Chuẩn Frobenius của R =", round(fro_norm, 3))


a) Nghiệm bằng np.linalg.solve():
 [2.788 1.529 1.188]

b) Định thức của R = 85.0
Ma trận R khả nghịch. Ma trận nghịch đảo:
 [[ 0.224  0.106 -0.047]
 [-0.059  0.235  0.118]
 [ 0.024 -0.094  0.153]]
Nghiệm bằng R^(-1) * b:
 [2.788 1.529 1.188]
Hai nghiệm giống nhau: True

c) Chuẩn Frobenius của R = 8.0
